# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170526_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=b'author_headshots'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Originally Published'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='null=False', max_length=100, verbose_name=b'Publisher'),
            preserve_default=False,
        ),
    ]
